import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
// import './globals.css'
// style + assets
import 'assets/scss/style.scss'

import AppLayout from 'layout/app.layout'

import React from 'react'
import { ReduxProvider } from 'app/redux-provider'

export const metadata: Metadata = {
    title: 'weave-Automate Web3 and Web2 Application',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ReduxProvider>
            <AppLayout>{children}</AppLayout>
        </ReduxProvider>
    )
}
